#!/usr/bin/env python3
"""Generate the baked-in BWSL standard-library module table."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


MODULES = [
    ("Color", "modules/Color.bwsl"),
    ("Compression", "modules/Compression.bwsl"),
    ("Debug", "modules/Debug.bwsl"),
    ("Globals", "modules/globals.bwsl"),
    ("Math", "modules/math.bwsl"),
    ("Noise", "modules/noise.bwsl"),
    ("Packing", "modules/Packing.bwsl"),
    ("PBR", "modules/PBR_module.bwsl"),
    ("PostFX", "modules/PostFX.bwsl"),
    ("Random", "modules/Random.bwsl"),
    ("Sampling", "modules/Sampling.bwsl"),
    ("SDF", "modules/SDF.bwsl"),
    ("Spaces", "modules/Spaces.bwsl"),
]

FNV_OFFSET_BASIS = 2166136261
FNV_PRIME = 16777619


def hash_str(text: str) -> int:
    value = FNV_OFFSET_BASIS
    for byte in text.encode("utf-8"):
        value ^= byte
        value = (value * FNV_PRIME) & 0xFFFFFFFF
    return value


def c_identifier(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def cpp_escape_bytes(value: bytes) -> str:
    escaped: list[str] = []
    for byte in value:
        if byte == ord("\\"):
            escaped.append("\\\\")
        elif byte == ord('"'):
            escaped.append('\\"')
        elif byte == ord("\n"):
            escaped.append("\\n")
        elif byte == ord("\r"):
            escaped.append("\\r")
        elif byte == ord("\t"):
            escaped.append("\\t")
        elif 32 <= byte <= 126:
            escaped.append(chr(byte))
        else:
            escaped.append(f"\\{byte:03o}")
    return "".join(escaped)


def load_module(repo_root: Path, name: str, rel_path: str) -> tuple[str, str]:
    path = repo_root / rel_path
    source = path.read_text(encoding="utf-8")
    match = re.search(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_]*)\b", source, re.MULTILINE)
    if not match:
        raise RuntimeError(f"{rel_path} does not declare a module")
    declared = match.group(1)
    if declared != name:
        raise RuntimeError(f"{rel_path} declares module {declared}, expected {name}")
    return rel_path, source


def generate(repo_root: Path, output: Path) -> None:
    entries = []
    for name, rel_path in MODULES:
        normalized_path, source = load_module(repo_root, name, rel_path)
        entries.append((name, normalized_path, source))

    lines: list[str] = [
        "#pragma once",
        "",
        "// Generated by scripts/gen_embedded_modules.py. Do not edit by hand.",
        "#include \"bwsl_defs.h\"",
        "",
        "namespace BWSL {",
        "namespace EmbeddedModules {",
        "",
        "struct ModuleSource {",
        "    u32 nameHash;",
        "    const char* name;",
        "    const char* virtualPath;",
        "    const char* source;",
        "    u32 sourceLength;",
        "};",
        "",
    ]

    for name, rel_path, source in entries:
        ident = c_identifier(name)
        lines.append(f"static constexpr const char k{ident}Source[] =")
        for source_line in source.splitlines(keepends=True):
            lines.append(f"    \"{cpp_escape_bytes(source_line.encode('utf-8'))}\"")
        if not source:
            lines.append('    ""')
        lines.extend(["    ;", ""])

    lines.extend(
        [
            "static constexpr ModuleSource kModules[] = {",
        ]
    )

    for name, rel_path, _source in entries:
        ident = c_identifier(name)
        lines.append(
            f"    {{0x{hash_str(name):08X}u, \"{name}\", \"stdlib://{rel_path}\", "
            f"k{ident}Source, static_cast<u32>(sizeof(k{ident}Source) - 1u)}},"
        )

    lines.extend(
        [
            "};",
            "",
            "static constexpr u32 kModuleCount = static_cast<u32>(sizeof(kModules) / sizeof(kModules[0]));",
            "",
            "inline const ModuleSource* FindByHash(u32 nameHash) {",
            "    for (u32 i = 0; i < kModuleCount; i++) {",
            "        if (kModules[i].nameHash == nameHash) {",
            "            return &kModules[i];",
            "        }",
            "    }",
            "    return nullptr;",
            "}",
            "",
            "} // namespace EmbeddedModules",
            "} // namespace BWSL",
            "",
        ]
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root containing the modules directory.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("core/bwsl_embedded_modules.generated.h"),
        help="Header path to write, relative to repo root unless absolute.",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    output = args.out if args.out.is_absolute() else repo_root / args.out
    generate(repo_root, output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
